sonar.projectKey=sc-vikvorona-test_test21
sonar.organization=sc-vikvorona-test

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.claude/**,**/projects/**,**/scripts/**,**/*.ts,**/*.tsx,**/*.json
sonar.typescript.tsconfigPath=scripts/tsconfig.json

sonar.coverage.exclusions=**/*
