#!/usr/bin/env python3
"""Code generator for the typescript-codegen-test fixture.

Reads codegen/entities.yaml and codegen/templates/*.ts.tmpl and writes:
  src/generated/<slug>/{model,repository,service,controller,validator,index}.ts
  tests/generated/<slug>.test.ts

Every generated file gets the AUTOGENERATED banner at the top so reviewers
(and the split-review fan-out filter) can distinguish them from the five
hand-written sources (entities.yaml + generate.py + the five templates).

Run from this directory:
    python3 generate.py
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml  # type: ignore[import-untyped]
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent
OUTPUT_SRC = PROJECT_ROOT / "src" / "generated"
OUTPUT_TESTS = PROJECT_ROOT / "tests" / "generated"
TEMPLATES_DIR = HERE / "templates"

BANNER = (
    "// AUTOGENERATED from codegen/entities.yaml + codegen/templates/{template}.\n"
    "// Regenerate via: python codegen/generate.py\n"
    "// Do not edit this file directly — changes will be lost on the next run.\n\n"
)


def field_type(name: str) -> str:
    """Infer the TS type for a field by its name (kept narrow on purpose)."""
    if name == "id" or name.endswith("Id") or name == "token" or name == "secret":
        return "string"
    if name.endswith("At"):
        return "Date | null"
    if name in {"verified", "active", "isPrivate", "isProtected", "isReadOnly", "enabled"}:
        return "boolean"
    if name in {
        "memberCount", "amountCents", "quantity", "rolloutPercent", "seats", "number",
        "downloadCount", "sizeCents", "priority",
    }:
        return "number"
    if name in {"scopes", "events", "approverIds"}:
        return "string[]"
    if name == "metadata":
        return "Record<string, unknown>"
    return "string"


def default_for(name: str) -> str:
    t = field_type(name)
    return {
        "string": "''",
        "number": "0",
        "boolean": "false",
        "string[]": "[]",
        "Date | null": "null",
        "Record<string, unknown>": "{}",
    }.get(t, "null")


def minimal_for(name: str) -> str:
    t = field_type(name)
    if t == "string":
        return f"'{name}-1'"
    if t == "number":
        return "1"
    if t == "boolean":
        return "false"
    if t == "string[]":
        return "[]"
    if t.startswith("Date"):
        return "null"
    if t.startswith("Record"):
        return "{}"
    return "null"


def render_field_lines(fields: list[str], *, optional: bool = False, exclude: set[str] | None = None) -> str:
    excl = exclude or set()
    out = []
    for f in fields:
        if f in excl:
            continue
        q = "?" if optional else ""
        out.append(f"  {f}{q}: {field_type(f)};")
    return "\n".join(out)


def render_defaults(fields: list[str]) -> str:
    return "\n".join(
        f"    {f}: input.{f} ?? {default_for(f)},"
        for f in fields if f != "id"
    )


def render_minimal_create(fields: list[str]) -> str:
    return "\n".join(
        f"  {f}: {minimal_for(f)},"
        for f in fields if f not in {"id", "createdAt"}
    )


def render_field_validators(fields: list[str]) -> str:
    lines = []
    for f in fields:
        if f == "id":
            continue
        t = field_type(f)
        if t == "string":
            lines.append(f"  if (input.{f} !== undefined && typeof input.{f} !== 'string') errors.push('{f} must be a string');")
        elif t == "number":
            lines.append(f"  if (input.{f} !== undefined && typeof input.{f} !== 'number') errors.push('{f} must be a number');")
        elif t == "boolean":
            lines.append(f"  if (input.{f} !== undefined && typeof input.{f} !== 'boolean') errors.push('{f} must be a boolean');")
        elif t == "string[]":
            lines.append(
                f"  if (input.{f} !== undefined && (!Array.isArray(input.{f}) || (input.{f} as string[]).some((x) => typeof x !== 'string'))) "
                f"errors.push('{f} must be string[]');"
            )
        elif t.startswith("Date"):
            lines.append(
                f"  if (input.{f} !== undefined && input.{f} !== null && !(input.{f} instanceof Date)) "
                f"errors.push('{f} must be a Date or null');"
            )
    return "\n".join(lines) if lines else "  // no validations"


def render_field_names(fields: list[str]) -> str:
    return "\n".join(f"    {f!r}," for f in fields)


def render_field_constants(fields: list[str]) -> str:
    return ", ".join(repr(f) for f in fields)


def render(template_name: str, **kwargs: str) -> str:
    template_path = TEMPLATES_DIR / f"{template_name}.tmpl"
    body = template_path.read_text()
    rendered = body.format(**kwargs)
    return BANNER.format(template=f"{template_name}.tmpl") + rendered


def emit(slug: str, klass: str, plural: str, fields: list[str]) -> None:
    ctx = {
        "slug": slug,
        "klass": klass,
        "plural": plural,
        "FIELD_LINES": render_field_lines(fields),
        "FIELD_LINES_OPTIONAL_NO_ID": render_field_lines(fields, optional=True, exclude={"id"}),
        "FIELD_LINES_REQUIRED_NO_ID_NO_CREATED": render_field_lines(fields, exclude={"id", "createdAt"}),
        "FIELD_NAMES_QUOTED": render_field_names(fields),
        "FIELD_CONSTANTS": render_field_constants(fields),
        "DEFAULTS": render_defaults(fields),
        "MINIMAL_CREATE": render_minimal_create(fields),
        "FIELD_VALIDATORS": render_field_validators(fields),
    }

    src_dir = OUTPUT_SRC / slug
    src_dir.mkdir(parents=True, exist_ok=True)
    (src_dir / "model.ts").write_text(render("model", **ctx))
    (src_dir / "repository.ts").write_text(render("repository", **ctx))
    (src_dir / "service.ts").write_text(render("service", **ctx))
    (src_dir / "controller.ts").write_text(render("controller", **ctx))
    (src_dir / "validator.ts").write_text(render("validator", **ctx))
    (src_dir / "index.ts").write_text(render("entity_index", **ctx))

    OUTPUT_TESTS.mkdir(parents=True, exist_ok=True)
    (OUTPUT_TESTS / f"{slug}.test.ts").write_text(render("test", **ctx))


def emit_root_index(entities: list[dict[str, object]]) -> None:
    """Aggregate every entity at src/generated/index.ts for a single import point."""
    lines: list[str] = []
    lines.append(BANNER.format(template="(root aggregator)"))
    for e in entities:
        slug = str(e["slug"])
        lines.append(f"export * from './{slug}';")
    (OUTPUT_SRC / "index.ts").write_text("\n".join(lines) + "\n")


def main() -> None:
    schema_path = HERE / "entities.yaml"
    schema = yaml.safe_load(schema_path.read_text())
    entities = schema["entities"]

    for e in entities:
        emit(e["slug"], e["klass"], e["plural"], e["fields"])
    emit_root_index(entities)

    print(f"Generated {len(entities)} entities into {OUTPUT_SRC.relative_to(PROJECT_ROOT)}")
    print(f"Generated {len(entities)} test files into {OUTPUT_TESTS.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
